version: '3'

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: amqp
    hostname: eddn-rabbit
    ports:
      - 5672:5672
    env_file: ".env"   # Git-Ignored, please generate a secure RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS along with this compose file